### ISSUE TITLE
uninitialized constant FactoryBotFactory::BaseFactory (NameError)

### ISSUE THREAD

**Issue by aaronkelton** [cdragon1116/factory_bot_factory#3]
After adding this gem to my Gemfile, and then `bundle install`, I get this error when I try `bundle exec rails console`
```
uninitialized constant FactoryBotFactory::BaseFactory (NameError)
```

**Comment by cdragon1116** [comment]
Hi, did you try download the latest version?

what are your rails & gem versions?

**Comment by enaoki** [comment]
I started to get this error too. Isn't missing `require 'factory_bot_factory/factories/base_factory.rb` in the [model_factory.rb](https://github.com/cdragon1116/factory_bot_factory/blob/main/lib/factory_bot_factory/factories/model_factory.rb)?

FWIW, I'm using Github Actions to test with `rspec` and suddenly this error started to show up. By 'suddenly', I mean that the action ran fine in my branch when I created the PR and when it after the merge, it failed with:

![image](https://user-images.githubusercontent.com/8048700/179876109-0ed718f6-01a7-4af5-8b54-925ffe1f8633.png)
